# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ignat/deadbeef-lyricbar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ignat/deadbeef-lyricbar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ignat/deadbeef-lyricbar/CMakeFiles /home/ignat/deadbeef-lyricbar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ignat/deadbeef-lyricbar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ddb_lyricbar_gtk2

# Build rule for target.
ddb_lyricbar_gtk2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ddb_lyricbar_gtk2
.PHONY : ddb_lyricbar_gtk2

# fast build rule for target.
ddb_lyricbar_gtk2/fast:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk2.dir/build.make CMakeFiles/ddb_lyricbar_gtk2.dir/build
.PHONY : ddb_lyricbar_gtk2/fast

#=============================================================================
# Target rules for targets named ddb_lyricbar_gtk3

# Build rule for target.
ddb_lyricbar_gtk3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ddb_lyricbar_gtk3
.PHONY : ddb_lyricbar_gtk3

# fast build rule for target.
ddb_lyricbar_gtk3/fast:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk3.dir/build.make CMakeFiles/ddb_lyricbar_gtk3.dir/build
.PHONY : ddb_lyricbar_gtk3/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk2.dir/build.make CMakeFiles/ddb_lyricbar_gtk2.dir/main.c.o
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk3.dir/build.make CMakeFiles/ddb_lyricbar_gtk3.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk2.dir/build.make CMakeFiles/ddb_lyricbar_gtk2.dir/main.c.i
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk3.dir/build.make CMakeFiles/ddb_lyricbar_gtk3.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk2.dir/build.make CMakeFiles/ddb_lyricbar_gtk2.dir/main.c.s
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk3.dir/build.make CMakeFiles/ddb_lyricbar_gtk3.dir/main.c.s
.PHONY : main.c.s

ui.o: ui.cpp.o

.PHONY : ui.o

# target to build an object file
ui.cpp.o:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk2.dir/build.make CMakeFiles/ddb_lyricbar_gtk2.dir/ui.cpp.o
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk3.dir/build.make CMakeFiles/ddb_lyricbar_gtk3.dir/ui.cpp.o
.PHONY : ui.cpp.o

ui.i: ui.cpp.i

.PHONY : ui.i

# target to preprocess a source file
ui.cpp.i:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk2.dir/build.make CMakeFiles/ddb_lyricbar_gtk2.dir/ui.cpp.i
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk3.dir/build.make CMakeFiles/ddb_lyricbar_gtk3.dir/ui.cpp.i
.PHONY : ui.cpp.i

ui.s: ui.cpp.s

.PHONY : ui.s

# target to generate assembly for a file
ui.cpp.s:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk2.dir/build.make CMakeFiles/ddb_lyricbar_gtk2.dir/ui.cpp.s
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk3.dir/build.make CMakeFiles/ddb_lyricbar_gtk3.dir/ui.cpp.s
.PHONY : ui.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk2.dir/build.make CMakeFiles/ddb_lyricbar_gtk2.dir/utils.cpp.o
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk3.dir/build.make CMakeFiles/ddb_lyricbar_gtk3.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk2.dir/build.make CMakeFiles/ddb_lyricbar_gtk2.dir/utils.cpp.i
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk3.dir/build.make CMakeFiles/ddb_lyricbar_gtk3.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk2.dir/build.make CMakeFiles/ddb_lyricbar_gtk2.dir/utils.cpp.s
	$(MAKE) -f CMakeFiles/ddb_lyricbar_gtk3.dir/build.make CMakeFiles/ddb_lyricbar_gtk3.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ddb_lyricbar_gtk2"
	@echo "... ddb_lyricbar_gtk3"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... ui.o"
	@echo "... ui.i"
	@echo "... ui.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

